### PING
GET http://localhost:8080/ping

### SIGNUP
POST http://localhost:8080/signUp
Content-Type: application/json

{
  "email": "marc@test.com",
  "password": "password"
}

### SIGNIN
POST http://localhost:8080/signIn
Content-Type: application/json

{
  "email": "marc@test.com",
  "password": "password"
}

> {% client.global.set("token", response.body.token) %}

### POST
POST http://localhost:8080/posts
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Title",
  "content": "Content"
}

### GET
GET http://localhost:8080/posts?page=3&limit=10&search=tit